SELECT t.*, A.SUBJECT_NAME AS SUBJECT1_NAME, B.SUBJECT_NAME AS SUBJECT2_NAME, G.SUBJECT_NAME AS SUBJECT3_NAME, E.SUBJECT_NAME AS SUBJECT4_NAME, F.SUBJECT_NAME AS SUBJECT5_NAME
FROM timetable t
INNER JOIN department d ON t.DEPARTMENT_ID = d.DEPARTMENT_ID
INNER JOIN course c ON t.COURSE_ID = c.COURSE_ID
LEFT JOIN subject A ON t.SUBJECT1 = A.SUBJECT_ID
LEFT JOIN subject B ON t.SUBJECT2 = B.SUBJECT_ID
LEFT JOIN subject G ON t.SUBJECT3 = G.SUBJECT_ID
LEFT JOIN subject E ON t.SUBJECT4 = E.SUBJECT_ID
LEFT JOIN subject F ON t.SUBJECT5 = F.SUBJECT_ID
WHERE d.DEPARTMENT_ID = '1'
AND c.COURSE_ID = '1'
AND t.SEMESTER = 'SEMESTER 1';

